### ISSUE TITLE
wrong main entry in package.json

### ISSUE THREAD

**Issue by punknroll** [srph/angular-timestamp-filter#1]
Hi, i think in package.json the entry "main": "index.js" should be

 "main": "src/filter.js"

greetz

**Comment by srph** [comment]
Good catch! :+1:

Although, I'm sure this library isn't yet available in npm which shouldn't be causing any issues.

**Comment by punknroll** [comment]
This setup automatically injects the required js files based on the main entry in the package.json so it's not just about npm.

https://github.com/Swiip/generator-gulp-angular

Good job anyway:-)

**Comment by srph** [comment]
Ah, thanks :smile: 

I get your point :smile:. Just a bit hesitant about making commits. Feel free to send a PR :grin:.

**Comment by srph** [comment]
https://github.com/srph/angular-timestamp-filter/commit/151c7b4cac9aa9800f5d278c7027ea980634cbd8.

Many thanks!
